todo_app/todo/urls.py
from django.urls import include, path
from .views import *

app_name = 'todo'

urlpatterns = [
    path('', login_redirect, name='start'),
    path('home/', home_page, name='home_page'),
    path('signup/', signup_user, name='signup_user'),
    path('login/', login_user, name='login_user'),
    path('logout/', logout_user, name='logout_user'),
    path('todo/<int:pk>', view_certain_todo, name='view_certain_todo'),
    path('update/<int:pk>', update_todo, name='update_todo'),
    path('delete/<int:pk>', delete_todo, name='delete_todo'),
    path('my_todos', view_my_todos, name='view_my_todos'),
    path('my_todos/add/', add_todo, name='add_todo'),
    path('my_todos/completed_todos', completed, name='completed'),
    path('my_todos/category/<str:title>', view_by_category, name='view_by_category')
]

todo_app/todo_app/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('todo.urls'))
]

todo_app/todo/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
# Create your models here.

class TodoModel(models.Model):
    title = models.CharField(max_length=200)
    important = models.BooleanField(default=False)
    done = models.BooleanField(default=False)
    description = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    photo = models.ImageField(upload_to='photos/%Y/%m/%d/', blank=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    category = models.ForeignKey('CategoryModel', on_delete=models.CASCADE, default=1)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('todo:view_certain_todo', args=[self.pk])


class CategoryModel(models.Model):
    title = models.CharField(max_length=100)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('todo:view_by_category', args=[self.title])

todo_app/todo/forms.py
from django import forms
from .models import TodoModel

class TodoForm(forms.ModelForm):
    # title = forms.CharField(max_length=200, widget=forms.TextInput(attrs={"class":"w-25 form-control"}))
    # description = forms.CharField(max_length=1000, widget=forms.Textarea(attrs={"class":"w-50 r-5 form-control"}))
    important = forms.BooleanField(required=False)
    class Meta():
        model = TodoModel
        fields = ["title", "description", 'important', 'category']
        widgets = {
                "title" : forms.TextInput(attrs={"class":"w-25 form-control"}),
                "description" : forms.Textarea(attrs={"class":"w-50 r-5 form-control"}),
                'category' : forms.Select(attrs={"class":"w-50 r-5 form-control"})
            }

class TodoUpdateForm(TodoForm):
    done = forms.BooleanField(required=False)
    fields = ["title", "description", 'important', 'category' 'done']

todo_app/todo/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.models import User
from django.db import IntegrityError
from .models import CategoryModel, TodoModel
from .forms import TodoForm, TodoUpdateForm
from django.contrib import messages
# Create your views here.


def home_page(request):
    return render(request, 'todo/home.html')



def signup_user(request):
    if request.method == 'GET':
        form = UserCreationForm()
        return render(request, 'todo/signup_user.html', {'form':form})
    else:
        if request.POST['password1'] == request.POST['password2']:
            try:
                user = User.objects.create_user(request.POST['username'], password=request.POST['password1'])
                user.save()
                login(request, user)
                messages.success(request, 'Your account was succesfully created')
                return redirect('todo:home_page')
            except IntegrityError:
                messages.error(request, 'Person with this nickname is already registered')
                return render(request, 'todo/signup_user.html', context={'form':UserCreationForm()})
        else:
            messages.error(request, 'You need to type in the exact same password twice')
            return render(request, 'todo/signup_user.html', context={'form':UserCreationForm()})


def login_user(request):
    form = AuthenticationForm()
    form.fields['username'].widget.attrs['class'] = "login__input"
    form.fields['password'].widget.attrs['class'] = "login__input"
    if request.method == 'POST':
        user = authenticate(request, username=request.POST['username'], password=request.POST['password'])
        if user is None:
            messages.error(request, 'No such user')
            return render(request, 'todo/login_user.html', context={'form': form})
        else:
            login(request, user)
            messages.success(request, 'Succesfully logged in')
            return redirect('todo:home_page')
    else:
        return render(request, 'todo/login_user.html', context={'form':form})


def logout_user(request):
    logout(request)
    messages.info(request, "You've been logged out. Please, log in if you want to proceed")
    return redirect('todo:login_user')

def view_my_todos(request):
    todos = TodoModel.objects.filter(user=request.user, done=False).order_by('-created_at')
    categorys = CategoryModel.objects.all()
    return render(request, 'todo/my_todos.html', context={'todos':todos, 'category':categorys})

def add_todo(request):
    if request.method == 'GET':
        form = TodoForm()
        return render(request, 'todo/add_todo.html', context={'form':form})
    else:
        form = TodoForm(request.POST)
        if form.is_valid():
            new_todo = TodoModel.objects.create(title=form.cleaned_data['title'], description=form.cleaned_data['description'], important=bool(request.POST.get('important', False)), category=form.cleaned_data['category'], user=request.user)
            new_todo.save()
            return redirect('todo:view_my_todos')
        else:
            return render(request, 'todo/add_todo.html', context={'form':form})

def update_todo(request, pk):
    todo = get_object_or_404(TodoModel, user=request.user, pk=pk)
    form = TodoUpdateForm(instance=todo)
    if request.method == 'GET':
        return render(request, 'todo/update_todo.html', context={'form':form, 'todo':todo})
    else:
        TodoModel.objects.filter(pk=pk, user=request.user).update(title=request.POST['title'], description=request.POST['description'], important=bool(request.POST.get('important', False)), done=bool(request.POST.get('done', False)), category=request.POST['category'])
        return redirect('todo:view_my_todos')

    # def update_todo(request, pk):
    # todo = get_object_or_404(TodoModel, user=request.user, pk=pk)
    # form = TodoForm(instance=todo)
    # if request.method == 'GET':
    #     return render(request, 'todo/update_todo.html', context={'form':form, 'todo':todo})
    # else:
    #     TodoModel.objects.filter(pk=pk, user=request.user).update(title=request.POST['title'], description=request.POST['description'], important=bool(request.POST.get('important', False)))
    #     return redirect('todo:view_my_todos')

def delete_todo(request, pk):
    de = get_object_or_404(TodoModel, user=request.user, pk=pk)
    messages.success(request, f'{de.title} succesfully deleted')
    de.delete()
    return redirect('todo:view_my_todos')

def view_certain_todo(request, pk):
    todo = get_object_or_404(TodoModel, pk=pk)
    return render(request, 'todo/view_certain_todo.html', context={'todo':todo})

def view_by_category(request, title):
    todos = TodoModel.objects.filter(category=CategoryModel.objects.get(title=title), user=request.user).select_related('category')
    return render(request, 'todo/todo_by_category.html', context={'todos':todos})

def completed(request):
    todos = TodoModel.objects.filter(user=request.user, done=True)
    return render(request, 'todo/completed.html', context={'todos':todos})


def login_redirect(request):
    if request.user.is_authenticated:
        return redirect('todo:home_page')
    else:
        return redirect('todo:login_user')

todo_app/templates/base.html
<!doctype html>
<html lang="en">
  <head>
    {% load static %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Bootstrap demo</title>
    <!-- <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"> -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
    <script src="https://kit.fontawesome.com/6eaadb5c81.js" crossorigin="anonymous"></script>
    <link rel="stylesheet" type="text/css" href="{% static 'css/custom.css' %}">
  </head>
  <body>
    {% block navbar %}{% endblock navbar %}
    {% if messages %}
           {% for message in messages %}
              {% if message.tags == 'error' %}
                <div class="alert alert-danger" role="alert">
                  {{ message }}
                </div>
              {% else %}
              <div class="alert alert-{{message.tags}}" role="alert">
                  {{ message }}
                </div>
              {% endif %}
           {% endfor %}
          {% endif %}
    {% block content %}
    <h1>Hello, world!</h1>
    {% endblock content %}
    {% block footer %}{% endblock footer %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe" crossorigin="anonymous"></script>
  </body>
</html>

todo_app/templates/inc/_nav.html
<div class="navbar-container">
<nav class="navbar navbar-expand-lg bg-body-red">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Navbar</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
      <div class="navbar-nav">
        <a class="nav-link active" aria-current="page" href="#">Home</a>
        <a class="nav-link" href="#">Features</a>
        <a class="nav-link" href="#">Pricing</a>
        <a class="nav-link disabled">Disabled</a>
      </div>
    </div>
    <p class="welcome-text">Welcome home, {{request.user.username|title}}</p>
    <form action="{% url 'todo:logout_user' %}">
            <button class="btn btn-secondary">Logout</button>
        </form>
  </div>
</nav>
</div>

todo_app/todo/templates/todo/add_todo.html
{% extends 'base.html' %}

{% block content %}
<h1>Create your todo</h1>

    <form action="{% url 'todo:add_todo' %}" method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Confirm post</button>
    </form>
{% endblock content %}

todo_app/todo/templates/todo/completed.html
{% extends 'base.html' %}
{% block content %}
<a href="{% url 'todo:view_my_todos' %}">To all todos</a>
{% for item in todos %}
<a href="{{ item.get_absolute_url }}"><h1>{{item.title}}</h1></a>
<p>{{item.description|truncatewords:15}}</p>
<p>{{item.created_at}}</p>
{% if item.important %}
<p>Important!</p>
{%endif%}
<p>{{item.done}}</p>
<p>Created: {{item.user.username}}</p>
<hr>
{% endfor %}
{% endblock content %}

todo_app/todo/templates/todo/home.html
{% extends 'base.html' %}

{% block content %}
<h1>start</h1>
<a href="{% url 'todo:view_my_todos' %}">Todos</a>
{% endblock content %}

todo_app/todo/templates/todo/login_user.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
	<div class="screen">
		<div class="screen__content">
            <form class="signup" action="{% url 'todo:signup_user' %}" method="GET">
            <button class="button-85">
                No account? Sign up!
            </button>
            </form>
			<form class="login" action="{% url 'todo:login_user' %}" method="POST">
                {% csrf_token %}
				<div class="login__field">
					<i class="login__icon fas fa-user"></i>
					{{ form.username }}
				</div>
				<div class="login__field">
					<i class="login__icon fas fa-lock"></i>
					{{form.password}}
				</div>
				<button type="submit" class="button login__submit">
					<span class="button__text">Log In Now</span>
					<i class="button__icon fas fa-chevron-right"></i>
				</button>				
			</form>
			<div class="social-login">
				<h3>log in via</h3>
				<div class="social-icons">
					<a href="#" class="social-login__icon fab fa-instagram"></a>
					<a href="#" class="social-login__icon fab fa-facebook"></a>
					<a href="#" class="social-login__icon fab fa-twitter"></a>
				</div>
			</div>
		</div>
		<div class="screen__background">
			<span class="screen__background__shape screen__background__shape4"></span>
			<span class="screen__background__shape screen__background__shape3"></span>		
			<span class="screen__background__shape screen__background__shape2"></span>
			<span class="screen__background__shape screen__background__shape1"></span>
		</div>		
	</div>
</div>
{% endblock content %}

todo_app/todo/templates/todo/my_todos.html
{% extends 'base.html' %}
{% block navbar %}
{% include 'inc/_nav.html' %}
{% endblock navbar %}
{% block content %}
<!-- <a href="{% url 'todo:add_todo' %}">Add todo</a>
{% for item in todos %}
<a href="{{ item.get_absolute_url }}"><h1>{{item.title}}</h1></a>
<p>{{item.description|linebreaks|truncatewords:15}}</p>
<p>{{item.created_at}}</p>
{% if item.important %}
<p>Important!</p>
{%endif%}
<p>{{item.done}}</p>
<p>Created: {{item.user.username}}</p>
<hr>
{% endfor %} -->
<div class="list-cont">
<div class="list-group">
    <a href="{% url 'todo:completed' %}">My completed todos</a>  <br>
    <a href="{% url 'todo:add_todo' %}">Add new todo</a>   <br>
    {% for cat in category %}
      <a href="{{cat.get_absolute_url}}">{{cat.title}}</a>
    {% endfor %}
    {% for item in todos %}
    {% if not item.important %}
    <a href="{{item.category.get_absolute_url}}"> <p>Category: {{item.category}}</p></a>
    <a href="{{ item.get_absolute_url }}" class="list-group-item list-group-item-action">
    <h5>{{item.title}}</h5>
    <p class="marg-parag">{{item.description|linebreaks|truncatewords:15}}</p>
    <p class="creation-date">{{item.created_at|date:'jS F Y'}}</p>
    </a>
    {% else %}
    <a href="{{item.category.get_absolute_url}}"> <p>Category: {{item.category}}</p></a>
    <a href="{{ item.get_absolute_url }}" class="list-group-item list-group-item-action list-group-item-warning">
    <h5>{{item.title}}</h5>
    <p class="marg-parag">{{item.description|linebreaks|truncatewords:15}}</p>
    <p class="creation-date">{{item.created_at|date:'jS F Y'}}</p>
  </a>
  {% endif %}
    {% endfor %}
</div>
</div>
{% endblock content %}
{% block footer %}
{% include 'inc/_footer.html' %}
{% endblock footer %}

todo_app/todo/templates/todo/signup_user.html
{% extends 'base.html' %}

{% block content %}
<h1>start</h1>

    <form action="{% url 'todo:signup_user' %}" method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Confirm sign up</button>
    </form>
{% endblock content %}

todo_app/todo/templates/todo/todo_by_category.html
{% extends 'todo/my_todos.html' %}

todo_app/todo/templates/todo/update_todo.html
{% extends 'base.html' %}

{% block content %}
<h1>Update your todo</h1>

    <form action="" method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Confirm update</button>
    </form>
{% endblock content %}

todo_app/todo/templates/todo/view_certain_todo.html
{% extends 'base.html' %}
{% block content %}
<a href="{% url 'todo:update_todo' todo.id %}">Update current todo</a>
<form action="{% url 'todo:delete_todo' todo.id %}">
    <button>Delete current todo</button>
</form>
<h1>{{todo.title}}</h1>
<p>{{todo.description}}</p>
<p>{{todo.created_at}}</p>
<p>Created: {{todo.user.username}}</p>
{% endblock content %}